# Site settings
title: Christian Cable
email: christiancable@gmail.com
description: "Christian Cable - web developer at the University of Kent"
baseurl: ""
url: "https://christiancable.co.uk"

# Build settings
markdown: kramdown
permalink: pretty

#sass 
sass:
    sass_dir: css
    style: compressed
