# Site settings
title: Christian Cable
email: christian.cable@lancaster.ac.uk
description: "Christian Cable - web developer at Lancaster University"
baseurl: ""
url: "http://lancaster.ac.uk/~cable"

# Build settings
markdown: kramdown
permalink: pretty
