# Site settings
title: Christian Cable
email: christian.cable@lancaster.ac.uk
description: "Christian Cable - web developer at Lancaster University"
baseurl: "/"
url: "http://christiancable.github.io/"

# Build settings
markdown: kramdown
permalink: pretty

#sass 
sass:
    sass_dir: css
    style: compressed